language: node_js
node_js:
  - "6.11"

install:
  - npm install

script:
  - npm run -s lint
  - npm run -s coverage
  - npm run -s report-coverage

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      tags: true
