language: node_js
node_js:
  - "8.9"

before_install:
  - echo -e "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

install:
  - npm install

script:
  - npm run -s lint
  - npm run -s coverage
  - npm run -s report-coverage

deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
      tags: true
